
# Setup
title:            QUANG NGUYEN
tagline:          'Mobile Craftsman'
description:      > # this means to ignore newlines until "baseurl:"
  A Software Craftsman
url:             https://quangctkm9207.github.io/
baseurl:          /

# gems:            [jekyll-paginate]
# paginate:        5
# paginate_path:   "page:num"

# Custom vars
version:          2.1.0

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
