
# Setup
title:            QUANG NGUYEN
tagline:          'Mobile Craftsman'
description:      'A Software Craftsman'
url:              https://emo-pass.com
newbaseurl:       /

# gems:            [jekyll-paginate]
# paginate:        5
# paginate_path:   "page:num"

# Custom vars
# version:          2.1.0

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
