
# Setup
title:            QUANG NGUYEN
tagline:          'Software Craftsman'
description:      'A Software Craftsman'
url:              https://emo-pass.com
newbaseurl:       /

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "/blog/page:num/"

gems:             [jemoji]

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
